ucm/config/routes.rb
Rails.application.routes.draw do
	get 'welcome/index'

	root 'welcome#index'

	resources :articles

end

ucm/app/models/article.rb
class Article < ActiveRecord::Base
	validates :title, presence: true, length: {minimum: 5}
end

ucm/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

ucm/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	
	def index
		@articles = Article.all
	end
		
	def show
		@article = Article.find(params[:id])
	end
	
	def new
		@article = Article.new
	end
	
	def edit
		@article = Article.find(params[:id])
	end
	
	def create
		# render plain: params[:article].inspect 
		
		@article = Article.new(article_params)
		if @article.save
			redirect_to @article
		else 
			render 'new'
		end
	end
	
	def update
		@article = Article.find(params[:id])
		
		if @article.update(article_params)
			redirect_to @article
		else
			render 'edit'
		end
	end
	
	def destroy
		@article = Article.find(params[:id])
		@article.destroy
		
		redirect_to articles_path
	end
	
	private 
		def article_params
			params.require(:article).permit(:title,:text)
		end
end

ucm/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

ucm/app/helpers/application_helper.rb
module ApplicationHelper
end

ucm/app/helpers/articles_helper.rb
module ArticlesHelper
end

ucm/app/helpers/welcome_helper.rb
module WelcomeHelper
end

ucm/app/views/articles/_form.html.erb
<%= form_for @article do |f| %>

	<% if @article.errors.any? %>
		<div id="error_explanation">
			<h2>
				<%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:
			</h2>
			<ul>
				<% @article.errors.full_messages.each do |msg| %>
					<li>
						<%= msg %>
					</li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</p>

	<p>
		<%= f.label :text %><br>
		<%= f.text_area :text %>
	</p>

	<p>
		<%= f.submit %>
	</p>
 
<% end %>

ucm/app/views/articles/edit.html.erb
<h1>
	<%= :title %> (editing)
</h1>

<%= link_to 'Back', articles_path %>

<%= render 'form' %>

ucm/app/views/articles/index.html.erb
<h1>Articles</h1>

<p>
	<%= link_to 'New Article', new_article_path %>
</p>
 
<% @articles.each do |article| %>
	<p>
		<%= link_to article.title, article_path(article) %>
		<%= link_to 'Edit', edit_article_path(article) %>
		<%= link_to 'Destroy', article_path(article),
              method: :delete,
              data: { confirm: 'Really destroy this article?' } %>
	</p>
<% end %>

ucm/app/views/articles/new.html.erb
<h1>New Article</h1>

<p>
	<%= link_to 'Back to Articles', articles_path %>
</p>

<%= render 'form' %>

ucm/app/views/articles/show.html.erb
<h1>
	<%= @article.title %>
</h1>

<p>
	<%= link_to 'Back to Articles', articles_path %>
</p>
 
<p>
	<%= link_to 'Edit', edit_article_path %>
</p>
 
<p>
	<%= @article.text %>
</p>

ucm/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ucm</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

ucm/app/views/welcome/index.html.erb
<h1>UCM</h1>

<p>
	<%= link_to 'Articles', controller: 'articles' %>
</p>